name: "ğŸŒ©ï¸ AliBaBa DevContainer, Features, and Templates"
on:
  workflow_dispatch:
  push:
    branches:
      - release/alibaba/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/skymodules/devcontainers/base
          cacheFrom: ghcr.io/skymodules/devcontainers/base
          push: always

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./alibaba/"
          generate-docs: "true"
          oc